name: docker

on:
  push:
    tags:
      - v**

jobs:
  docker:
    name: Build and publish docker image
    uses: ./.github/workflows/docker-reusable.yml
    with:
      image_name: subsquid/sqd-portal
      push_latest: true
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
